server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true
      enabled: true

  port: 4100

  tomcat:
    uri-encoding: UTF-8
    max-connections: 20000
    threads:
      max: 2000
      min-spare: 30

spring:
  redis:
    host: 192.168.31.244

  logging:
    file:
      name:/LearnLruCache/log/learnlrucache.log
    level:
      com.learn.lrucache:debug

